// The Spanish text of the UI, by its English text. See i18n.ts. Technical
// words that people don't translate, like tracker, torrent, ratio and
// freeleech, stay as they are.
export const ES: Record<string, string> = {
  "1 torrent matches": "1 torrent coincide",
  "12-hour": "12 horas",
  "24-hour": "24 horas",
  "API key": "Clave de API",
  "API keys": "Claves de API",
  "About {name}": "Acerca de {name}",
  "Access token": "Token de acceso",
  "Actions": "Acciones",
  "Actions for {name}": "Acciones de {name}",
  "Add a domain": "Agrega un dominio",
  "Add a rule to watch a tracker's ratio": "Agrega una regla para vigilar el ratio de un tracker",
  "Add rule": "Agregar regla",
  "Add upload (GiB)": "Agregar subida (GiB)",
  "Address": "Dirección",
  "After release": "Tras liberar",
  "All": "Todo",
  "Any downloads it holds are released.": "Las descargas que retiene se liberan.",
  "Below {hold} downloads pause, above {release} they continue.":
    "Por debajo de {hold} las descargas se pausan, por encima de {release} continúan.",
  "Bought so far {size}": "Comprado hasta ahora {size}",
  "Browser's time zone ({zone})": "Zona horaria del navegador ({zone})",
  "Buffer": "Margen",
  "Can't connect": "Sin conexión",
  "Cancel": "Cancelar",
  "Change": "Cambiar",
  "Change password": "Cambiar contraseña",
  "Change quota": "Cambiar cuota",
  "Change quota · {name}": "Cambiar cuota · {name}",
  "Change the indexer's sync profile when held": "Cambia el perfil de sincronización del indexador al retener",
  "Clock": "Reloj",
  "Coming soon": "Próximamente",
  "Connect": "Conectar",
  "Connect {name}": "Conectar {name}",
  "Connected": "Conectado",
  "Connected · {version}": "Conectado · {version}",
  "Connecting": "Conectando",
  "Copied {count} lines": "{count} líneas copiadas",
  "Copy visible lines": "Copiar las líneas visibles",
  "Couldn't change the password": "No se pudo cambiar la contraseña",
  "Couldn't change {domain}'s quota": "No se pudo cambiar la cuota de {domain}",
  "Couldn't copy the logs": "No se pudieron copiar los registros",
  "Couldn't delete {name}": "No se pudo eliminar {name}",
  "Couldn't pause {name}": "No se pudo pausar {name}",
  "Couldn't pin {domain}": "No se pudo fijar {domain}",
  "Couldn't resume {name}": "No se pudo reanudar {name}",
  "Couldn't save {name}": "No se pudo guardar {name}",
  "Couldn't sign out": "No se pudo cerrar la sesión",
  "Couldn't test {name}": "No se pudo probar {name}",
  "Couldn't unpin {domain}": "No se pudo desfijar {domain}",
  "Current password": "Contraseña actual",
  "Dashboard": "Panel",
  "Delete": "Eliminar",
  "Delete rule": "Eliminar regla",
  "Delete {name}?": "¿Eliminar {name}?",
  "Domains": "Dominios",
  "Domains or announce URLs, comma-separated": "Dominios o URLs de announce, separados por comas",
  "Download {bytes} more and it holds": "Descarga {bytes} más y se retiene",
  "Downloaded": "Descargado",
  "Downloaded against what its upload allows": "Descargado frente a lo que permite su subida",
  "Downloads a rule holds show up here": "Las descargas que retiene una regla aparecen aquí",
  "Downloads don't count and nothing is held": "Las descargas no cuentan y nada se retiene",
  "Downloads don't count during the freeleech": "Las descargas no cuentan durante el freeleech",
  "Duration": "Duración",
  "Edit": "Editar",
  "Edit address": "Editar dirección",
  "Edit rule": "Editar regla",
  "Edit {name}": "Editar {name}",
  "Ends in {time}": "Termina en {time}",
  "Ends when saved": "Termina al guardar",
  "Enter 1 to {max} hours": "Ingresa de 1 a {max} horas",
  "Enter a name": "Ingresa un nombre",
  "Enter a ratio above 0": "Ingresa un ratio mayor que 0",
  "Enter a topic": "Ingresa un topic",
  "Enter an address": "Ingresa una dirección",
  "Error": "Error",
  "Event": "Evento",
  "Filter": "Filtrar",
  "Filter by name": "Filtrar por nombre",
  "Filter logs": "Filtrar registros",
  "Filter trackers": "Filtrar trackers",
  "Freeleech": "Freeleech",
  "General": "General",
  "Held": "Retenido",
  "Held torrents": "Torrents retenidos",
  "Hide": "Ocultar",
  "Hold below": "Retener por debajo de",
  "Holds below a {ratio} ratio": "Retiene por debajo de un ratio de {ratio}",
  "Holds, releases and changes show up here": "Las retenciones, liberaciones y cambios aparecen aquí",
  "Indexer": "Indexador",
  "Info": "Info",
  "Integrations": "Integraciones",
  "Language": "Idioma",
  "Left before the next hold or release": "Lo que falta para la próxima retención o liberación",
  "Limits it to 1 KiB/s, keeps seeding": "Lo limita a 1 KiB/s, sigue sembrando",
  "Live": "En vivo",
  "Loading": "Cargando",
  "Log retention": "Retención de registros",
  "Logs": "Registros",
  "Logs what would be held or released, and changes nothing": "Registra lo que se retendría o liberaría, y no cambia nada",
  "Lowest level shown": "Nivel más bajo mostrado",
  "Matches": "Coincide con",
  "Max {size} to keep the ratio": "Máx. {size} para mantener el ratio",
  "Must be above Hold below": "Debe ser mayor que Retener por debajo de",
  "Name": "Nombre",
  "New password": "Contraseña nueva",
  "New rule": "Nueva regla",
  "Next": "Sig.",
  "No events yet": "Aún no hay eventos",
  "No limit": "Sin límite",
  "No matching lines": "No hay líneas que coincidan",
  "No matching trackers": "No hay trackers que coincidan",
  "No password": "Sin contraseña",
  "No rule": "Sin regla",
  "No rule, so no limit": "Sin regla, así que sin límite",
  "No rules yet": "Aún no hay reglas",
  "No trackers yet": "Aún no hay trackers",
  "None": "Sin definir",
  "Not connected": "Sin conectar",
  "Nothing is held": "No hay nada retenido",
  "Notifications": "Notificaciones",
  "OK": "OK",
  "Only {size} was bought": "Solo se compraron {size}",
  "Open logs": "Abrir registros",
  "Pages": "Páginas",
  "Password": "Contraseña",
  "Password changed": "Se cambió la contraseña",
  "Password removed": "Se quitó la contraseña",
  "Password set": "Se definió la contraseña",
  "Pause rule": "Pausar regla",
  "Paused": "En pausa",
  "Pin tracker": "Fijar tracker",
  "Pin {name}, {status}": "Fijar {name}, {status}",
  "Poll interval": "Intervalo de consulta",
  "Prev": "Ant.",
  "Progress": "Progreso",
  "Ratio": "Ratio",
  "Ratio {ratio}": "Ratio {ratio}",
  "Ratio {ratio} → {next}": "Ratio {ratio} → {next}",
  "Recent events": "Eventos recientes",
  "Release above": "Liberar por encima de",
  "Releases above a {ratio} ratio": "Libera por encima de un ratio de {ratio}",
  "Remove": "Quitar",
  "Remove password": "Quitar contraseña",
  "Repeat the new password": "Repite la contraseña nueva",
  "Resume rule": "Reanudar regla",
  "Rule": "Regla",
  "Rules": "Reglas",
  "Save": "Guardar",
  "Security": "Seguridad",
  "Select the lines and copy them by hand.": "Selecciona las líneas y cópialas a mano.",
  "Sent": "Enviado",
  "Set": "Definir",
  "Set password": "Definir contraseña",
  "Settings": "Ajustes",
  "Settings sections": "Secciones de ajustes",
  "Show": "Mostrar",
  "Sign in": "Iniciar sesión",
  "Sign out": "Cerrar sesión",
  "Stop": "Detener",
  "Stops the download": "Detiene la descarga",
  "System": "Sistema",
  "Test": "Probar",
  "Test mode": "Modo de prueba",
  "Testing": "Probando",
  "The passwords don't match": "Las contraseñas no coinciden",
  "They show up once qBittorrent connects": "Aparecen cuando qBittorrent se conecta",
  "Throttle": "Limitar",
  "Time": "Hora",
  "Time zone": "Zona horaria",
  "Topic": "Topic",
  "Torrent": "Torrent",
  "Tracker": "Tracker",
  "Trackers": "Trackers",
  "Trackers pages": "Páginas de trackers",
  "Try another level or filter": "Prueba otro nivel u otro filtro",
  "Try another name": "Prueba otro nombre",
  "Unchanged": "Sin cambios",
  "Unpin tracker": "Desfijar tracker",
  "Unpin {name}, {status}": "Desfijar {name}, {status}",
  "Update {secret}": "Actualizar {secret}",
  "Upload {bytes} more to release": "Sube {bytes} más para liberar",
  "Uploaded over downloaded": "Subido entre descargado",
  "Use at least {count} characters": "Usa al menos {count} caracteres",
  "Use up to 64 letters, numbers, - and _": "Usa hasta 64 letras, números, - y _",
  "Warn": "Aviso",
  "When held": "Al retener",
  "While held": "Mientras está retenido",
  "Would hold below a {ratio} ratio": "Retendría por debajo de un ratio de {ratio}",
  "Yesterday": "Ayer",
  "access token": "token de acceso",
  "paused": "en pausa",
  "qBittorrent has no torrents": "qBittorrent no tiene torrents",
  "to download until hold": "por descargar hasta la retención",
  "to upload until release": "por subir hasta la liberación",
  "updated {seconds} s ago": "actualizado hace {seconds} s",
  "{count} days": "{count} días",
  "{count} torrents match": "{count} torrents coinciden",
  "{days}d ago": "hace {days} d",
  "{domain} isn't a domain": "{domain} no es un dominio",
  "{domain} pinned": "Se fijó {domain}",
  "{domain} quota saved": "Se guardó la cuota de {domain}",
  "{domain} unpinned": "Se desfijó {domain}",
  "{first}–{last} of {total}": "{first}–{last} de {total}",
  "{hours}h ago": "hace {hours} h",
  "{minutes}m ago": "hace {minutes} min",
  "{name} added": "Se agregó {name}",
  "{name} deleted": "Se eliminó {name}",
  "{name} paused": "Se pausó {name}",
  "{name} resumed": "Se reanudó {name}",
  "{name} saved": "Se guardó {name}",
  "{time} left": "quedan {time}",
};
